### ISSUE TITLE
Trouver un nom pour l'API

### ISSUE THREAD

**Issue by amrosu** [gmaillet/ign-api-mosaique#18]
Mes premières idées :
Opack - Ortho package
OPALE - OrthoPhotos Aériennes [Livrées par] Entrepôt

**Comment by amrosu** [comment]
PackO

**Comment by gmaillet** [comment]
> PackO - assez évident (j'ai inversé Opack) et ça sonne mieux que "Opack" (qui a en plus une mauvaise connotation)

Oui, ça sonne bien. 
Je me demande si on prend packo ou carrément paco pour éviter de se prendre la tête avec le K?

**Comment by amrosu** [comment]
J'avoue que j'aime bien le K dedans, mais je suis d'accord que c'est plus simple sans

**Comment by gmaillet** [comment]
on valide PackO
